# Generated by Django 4.2 on 2023-04-26 02:11

import apps.usuario.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=250, verbose_name="Nome")),
                (
                    "hash_password",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Senha em Hash",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "foto_perfil",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[300, 300],
                        upload_to=apps.usuario.models.path_and_rename,
                        verbose_name="Upload Imagem",
                    ),
                ),
                (
                    "codigo_recuperacao",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        verbose_name="Código de Recuperação",
                    ),
                ),
                ("last_login", models.DateTimeField(verbose_name="Último Login Em")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado Em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado Em"),
                ),
            ],
        ),
    ]
