# Generated by Django 4.2 on 2023-04-27 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario", options={"verbose_name": "Usuário"},
        ),
    ]
